publish_to: none
name: electronic_id_card_example
description: An example app demonstrating the electronic_id_card package.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  electronic_id_card:
    path: ../

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^4.0.0

